# Generated by Django 5.2 on 2025-05-17 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_patient_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
