# Generated by Django 5.2 on 2025-05-28 10:30

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('exam_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения экзамена')),
                ('exam_image', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Задание (изображение)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('examinees', models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='Экзаменуемые')),
            ],
            options={
                'verbose_name': 'Экзамен (АБ)',
                'verbose_name_plural': 'Экзамены (АБ)',
                'ordering': ['-exam_date', 'exam_name'],
            },
        ),
    ]
